# -*- coding: utf-8 -*-
"""MODEL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1LVcemkjVUJC9rpJQPlFC37G1yRi9cp
"""

# ======================================================================
# 📦 Pharmacy Sales Forecasting using Optimized BiLSTM
# ======================================================================
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Bidirectional, Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import joblib
import math

# ======================================================================
# 1️⃣ Load & Preprocess Dataset
# ======================================================================
df = pd.read_csv("pharmacy_sales_with_code_predictive_v2.csv")

# Rename columns for consistency
df.rename(columns={
    "Product_Code": "productCode",
    "Sold_Quantity": "quantity",
    "Division": "division",
    "Date": "date",
    "Pharmacy_ID": "zone"
}, inplace=True)

# Convert date column
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Sort by product, zone, and date
df = df.sort_values(by=["productCode", "zone", "date"])

# Encode categorical features
product_encoder = LabelEncoder()
division_encoder = LabelEncoder()
df["product_enc"] = product_encoder.fit_transform(df["productCode"])
df["division_enc"] = division_encoder.fit_transform(df["division"])

# Scale target column
scaler = MinMaxScaler()
df["quantity_scaled"] = scaler.fit_transform(df[["quantity"]])

# ======================================================================
# 2️⃣ Prepare Sequences for BiLSTM
# ======================================================================
sequence_length = 14  # Two-week lookback
X, y = [], []

for key, group in df.groupby(["productCode", "zone"]):
    group = group.reset_index(drop=True)
    for i in range(len(group) - sequence_length):
        seq = group.iloc[i:i+sequence_length][["quantity_scaled", "product_enc", "division_enc"]].values
        target = group.iloc[i+sequence_length]["quantity_scaled"]
        X.append(seq)
        y.append(target)

X, y = np.array(X), np.array(y)

print("✅ Shapes after sequence preparation:")
print("X shape:", X.shape)
print("y shape:", y.shape)

# ======================================================================
# 3️⃣ Split Data into Train/Test
# ======================================================================
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# ======================================================================
# 4️⃣ Build Optimized BiLSTM Model
# ======================================================================
model = Sequential([
    Input(shape=(sequence_length, 3)),
    Bidirectional(LSTM(128, activation='tanh', return_sequences=True)),
    Dropout(0.2),
    Bidirectional(LSTM(64, activation='tanh', return_sequences=False)),
    Dense(32, activation='relu'),
    Dense(1)
])

model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

# ======================================================================
# 5️⃣ Train the BiLSTM Model
# ======================================================================
es = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=15,
    batch_size=32,
    callbacks=[es],
    verbose=1
)

# ======================================================================
# 6️⃣ Predict and Evaluate
# ======================================================================
y_pred_scaled = model.predict(X_test)
y_true = scaler.inverse_transform(y_test.reshape(-1, 1)).flatten()
y_pred = scaler.inverse_transform(y_pred_scaled.reshape(-1, 1)).flatten()

# Evaluation Metrics
mse = mean_squared_error(y_true, y_pred)
rmse = math.sqrt(mse)
mae = mean_absolute_error(y_true, y_pred)
r2 = r2_score(y_true, y_pred)

print("\n📊 BiLSTM Model Evaluation Metrics")
print(f"MSE  : {mse:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"R²   : {r2:.4f}")

# ======================================================================
# 7️⃣ Predict Future Sales Function (Alert System)
# ======================================================================
def predict_sales_by_date(product_code, current_quantity, division, input_date,
                          model, scaler, product_encoder, division_encoder, threshold=400):

    # Handle unseen labels safely
    if product_code not in product_encoder.classes_:
        product_encoder.classes_ = np.append(product_encoder.classes_, product_code)
    if division not in division_encoder.classes_:
        division_encoder.classes_ = np.append(division_encoder.classes_, division)

    # Encode inputs
    product_encoded = product_encoder.transform([product_code])[0]
    division_encoded = division_encoder.transform([division])[0]
    qty_scaled = scaler.transform([[current_quantity]])[0][0]

    # Ensure date exists
    if input_date not in df["date"].values:
        raise ValueError(f"❌ Date {input_date} not found in dataset")

    idx = df.index[df["date"] == input_date][0]
    if idx < sequence_length - 1:
        raise ValueError("❌ Not enough past data for this date")

    # Prepare past 14 days window
    past_window = df[["quantity_scaled", "product_enc", "division_enc"]].iloc[idx - (sequence_length - 1):idx].values

    # Add today’s info
    new_window = np.vstack([past_window, [qty_scaled, product_encoded, division_encoded]])
    new_window = new_window[-sequence_length:]

    X_input = new_window.reshape((1, new_window.shape[0], new_window.shape[1]))

    # Predict next day sales
    y_pred = model.predict(X_input)
    next_day_qty = scaler.inverse_transform(y_pred[:, 0].reshape(-1, 1))[0][0]

    # Prepare previous window (for comparison)
    prev_window = past_window[:-1]
    X_prev = prev_window.reshape((1, prev_window.shape[0], prev_window.shape[1]))
    y_prev = model.predict(X_prev)
    prev_day_qty = scaler.inverse_transform(y_prev[:, 0].reshape(-1, 1))[0][0]

    combined = {
        "Previous_Day_Sales": prev_day_qty,
        "Today_Sales": current_quantity,
        "Next_Day_Sales": next_day_qty
    }

    alert = any(value > threshold for value in combined.values())
    return combined, alert

# ======================================================================
# 🧾 User Input Section
# ======================================================================
today_product = input("Enter Product Code (e.g., P001, P002): ")
today_sales = int(input("Enter today's sales quantity: "))
today_division = input("Enter today's division (North/South/East/West/Central): ")
today_date = input("Enter today's date (YYYY-MM-DD): ")
today_date = pd.to_datetime(today_date)

results, alert_flag = predict_sales_by_date(
    today_product,
    today_sales,
    today_division,
    today_date,
    model,
    scaler,
    product_encoder,
    division_encoder,
    threshold=400
)

print("\n📊 Sales Summary:")
for k, v in results.items():
    print(f"{k}: {v:.2f}")

if alert_flag:
    print("🚨 ALERT: One of the days exceeded the threshold!")
else:
    print("✅ All sales within safe range")

# ======================================================================
# 💾 Save Model and Encoders
# ======================================================================
model.save("bilstm_sales_model_optimized.h5")
joblib.dump(product_encoder, "product_encoder_v2.pkl")
joblib.dump(division_encoder, "division_encoder_v2.pkl")
joblib.dump(scaler, "scaler_v2.pkl")

print("\n✅ BiLSTM model and encoders saved successfully.")
# ======================================================================